### ISSUE TITLE
Cannot download the CAMERA Datasets

### ISSUE THREAD

**Issue by CAN-Lee** [sahithchada/NOCS_PyTorch#3]
do you meet this problem? thanks
kantleecan@gmail.com

**Comment by bharathsivaram10** [comment]
How are you trying to download them? We did it on a Linux platform, so wget "dataset.zip" should work

**Comment by CAN-Lee** [comment]
@bharathsivaram10 Really appreciate it. It works. I failed to download them from Chrome several times.

**Comment by bharathsivaram10** [comment]
Good to hear it worked!
