### ISSUE TITLE
Questions for consultation

### ISSUE THREAD

**Issue by xyb-sia** [sahithchada/NOCS_PyTorch#4]
Hello, I have seen your work and it has been very helpful to me. Thank you for sharing. There is a place I need to consult, what is the use of r ['coords'] [:,:,:, 2]=1-r ['coords'] [:,:,:, 2] in demo_eval.py, instead of directly using r ['coords']？

**Comment by bharathsivaram10** [comment]
Hi, I'm glad you found the code helpful.

I can't recall exactly why we did that, but I can say it has something to do with flipping the z-axis of the coord map.
If you look at [line 461 of dataset.py](https://github.com/sahithchada/NOCS_PyTorch/blob/f4ed85efec3b39476bda74ef84a314fcbcf8f0b3/dataset.py#L461), the same thing is done (except it is commented!)

So you could try seeing what the demo img looks like if you don't do the z-axis flipping. We may have just done it for visualization purposes?

**Comment by bharathsivaram10** [comment]
Closed due to inactivity
