### ISSUE TITLE
where is the "self.image_info" initialized in dataset.py?

### ISSUE THREAD

**Issue by lijunbo-code** [sahithchada/NOCS_PyTorch#7]
![image](https://github.com/sahithchada/NOCS_PyTorch/assets/152573941/50f8eb84-421d-4074-b514-5076128eccfb)
In your code, self.image_info plays an important role in many functions when loading the dataset. However, I haven't found any function or code snippet that initializes image_info. This has caused the inference or training program to fail to run successfully. How can this issue be resolved?

**Comment by sahithchada** [comment]
Check this method
https://github.com/sahithchada/NOCS_PyTorch/blob/f4ed85efec3b39476bda74ef84a314fcbcf8f0b3/utils.py#L169
self.image_info is updated for every image that is added to the dataset.

**Comment by bharathsivaram10** [comment]
To expand on Sahith's answer, the NOCSData class inherits the utils.Dataset class. Here, we call the load_camera_scenes function of the NOCSData class:
https://github.com/sahithchada/NOCS_PyTorch/blob/f4ed85efec3b39476bda74ef84a314fcbcf8f0b3/train.py#L254

Looking closer at that function, we is it calls:
https://github.com/sahithchada/NOCS_PyTorch/blob/f4ed85efec3b39476bda74ef84a314fcbcf8f0b3/dataset.py#L308

which is a function of the utils.Dataset class. And we see that is where the image_info is appended
https://github.com/sahithchada/NOCS_PyTorch/blob/f4ed85efec3b39476bda74ef84a314fcbcf8f0b3/utils.py#L175

Hope this helps!
